In [13]:
import cv2

image = cv2.imread("calibration.jpg")
print(image.shape)

(240, 320, 3)


In [1]:
import cv2

# 全局变量保存四个点的坐标
points = []

# 鼠标回调函数：点击左键记录坐标
def mouse_callback(event, x, y, flags, param):
    global points
    if event == cv2.EVENT_LBUTTONDOWN:
        points.append((x, y))
        print(f"Selected point: ({x}, {y})")
        if len(points) == 4:
            print("All points selected. Press 'q' to exit.")

# 读取图像并显示
image = cv2.imread("calibration.jpg")
cv2.namedWindow("Select Points", cv2.WINDOW_NORMAL)
cv2.resizeWindow("Select Points", 640, 480)
cv2.setMouseCallback("Select Points", mouse_callback)

while True:
    img_display = image.copy()
    # 绘制已选点
    for p in points:
        cv2.circle(img_display, p, 5, (0, 0, 255), -1)
    cv2.imshow("Select Points", img_display)
    key = cv2.waitKey(1) & 0xFF
    if key == ord('q') or len(points) >= 4:
        break

cv2.destroyAllWindows()
print("Final points:", points)

Selected point: (133, 103)
Selected point: (198, 104)
Selected point: (225, 144)
Selected point: (106, 142)
All points selected. Press 'q' to exit.
Final points: [(133, 103), (198, 104), (225, 144), (106, 142)]


In [5]:
import cv2
import numpy as np

# 读取矫正图像
image = cv2.imread("calibration.jpg")
h, w = image.shape[:2]

# 定义原始图像的四个角点（需手动标注或通过算法检测）
src_points = np.float32([[134, 103], [199, 104], [226, 144], [106, 143]])

# 定义鸟瞰图中的目标位置（通常为矩形）
dst_points = np.float32([
    [w/2-40, h-240],          # 左上角
    [w/2+40, h-240],          # 右上角
    [w/2+40, h-120],          # 右下角
    [w/2-40, h-120]           # 左下角
])

# 计算透视变换矩阵
matrix = cv2.getPerspectiveTransform(src_points, dst_points)
np.save("perspective_matrix.npy", matrix)
print(matrix)

[[-1.04096457e+00 -3.06287902e+00  3.45767492e+02]
 [ 7.70800805e-02 -5.01020523e+00  5.05722408e+02]
 [ 4.53853096e-04 -1.91340013e-02  1.00000000e+00]]


In [8]:
# 应用透视变换
birdseye = cv2.warpPerspective(image, matrix, (w, h))

# 显示结果
cv2.namedWindow("Original", cv2.WINDOW_NORMAL)      # 允许调整窗口
cv2.resizeWindow("Original", 320, 240)              
cv2.imshow("Original", image)

cv2.namedWindow("Birdseye View", cv2.WINDOW_NORMAL)  # 允许调整窗口
cv2.resizeWindow("Birdseye View", 320, 240)         
cv2.imshow("Birdseye View", birdseye)

cv2.waitKey(0)
cv2.destroyAllWindows()